spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STATISTICS
          uri: lb://STATISTICS
          predicates:
            - Path=/statistics/**

# HTTP Server
server:
  port: 8080

# Cloud
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/