spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STATISTICS-SERVICE
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/country/*
          filters:
            - name: CircuitBreaker
              args:
                name: STATISTICS-SERVICE
                fallbackuri: forward:/statisticsFallBack

#hystrix:
#  command:
#    execution:
#      isolation:
#        thread:
#          timeoutInMilliseconds: 2000

# HTTP Server
server:
  port: 8080

# Cloud
cloud:
  registry:
    url: localhost
    port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${cloud.registry.url}:${cloud.registry.port}/eureka/