spring:
  application:
    name: DATA-STORE-SERVICE

  datasource:
    url: jdbc:h2:mem:dev
  h2.console:
    enabled: true

  rabbitmq:
    addresses: localhost
    port: 5672
    password: guest
    username: guest

# messaging
messaging:
  queue: queue
  exchange: exchange
  routingKey: routing_key

# HTTP
server:
  port: 8081

# Cloud
cloud:
  registry:
    url: localhost
    port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${cloud.registry.url}:${cloud.registry.port}/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic

# Swagger
springdoc.swagger-ui.path: "swagger.html"